language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t svisagan83/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true svisagan83/react-test npm test

after_sucess:
  - docker build -t svisagan83/multi-client ./client
  - docker build -t svisagan83/multi-nginx ./nginx
  - docker build -t svisagan83/multi-server ./server
  - docker build -t svisagan83/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push svisagan/multi-client
  - docker push svisagan/multi-nginx
  - docker push svisagan/multi-server
  - docker push svisagan/multi-worker