language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t svisagan83/react-test -f ./client/Dockerfile.dev ./client

script:
 # - docker run -e CI=true svisagan83/react-test npm test
 - docker run svisagan83/react-test npm test -- --coverage

after_success:
  - docker build -t svisagan/multi-client ./client
  - docker build -t svisagan/multi-nginx ./nginx
  - docker build -t svisagan/multi-server ./server
  - docker build -t svisagan/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push svisagan/multi-client
  - docker push svisagan/multi-nginx
  - docker push svisagan/multi-server
  - docker push svisagan/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-636402340807
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

